server:
  port: 42095
  servlet:
    context-path: /manager

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


shiro:
  successUrl: "/success"

cas:
  successUrlPattern: "/loginCas"
  casFilterUrlPattern: "/user"
  serviceUrl: "http://127.0.0.1:${server.port}${server.servlet.context-path}"
